
---
deployments:
  - name: "my-deployment"

    ## -- Additional Kubernetes Ressources
    # Doc:


    ## -- Reckoner Definition
    reckoner:
      ## -- Current Context
      context: (( grab $.clusters.0.name ))

      ## -- Default Namespace
      #namespace: 'rook-system'

      ## -- Default Charts
      charts:
        rook-operator:
          version: "1.0.0"
          repository: "k8n-stable"
          namespace: "kube-system"

values:
  some:
    super: "cool"
    values:
      that: influence
    my:
      application: deployment

  ## -- Reference a Secret from secrets.ejson
  database_password: (( grab $.SECRETS.db_password ))
